language: python
python:
 - "2.7"
 - "2.6" 
 - "2.7" 
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
 - "pypy3"
services:
  - memcached
  
archive: true
install: python setup.py install

before_script: pip install nose
script: nosetests
build_image: drydock/u14pytall:tip
